fixed useContext by wrapping the provider around the children in root…
cindyquach12/beautyhub pull request #20
Opened 2024-06-21 23:54 UTC by cvogitgud

… layout, and added a custom hook to use the LocationAndService context to decrease the amount of imports

2024-06-21 23:56 UTC, cvogitgud commented
To use the context as it's set up right now:
1. in the component/page you want to use the state variables in the context, import the hook `useLocationAndServices` from the context file.
2. extract the properties/variables you want from the return of `useLocationAndServices()`
3. use them!

2024-06-22 00:34 UTC, cindyquach12 approved these changes

2024-06-22 00:34 UTC, cindyquach12 commented on app/contexts/location-and-service/LocationAndService.context.tsx
> +    const props = {
Great job!! Let's keep this const as `value` since it reflects the values of our object. `props` is a little too generic and hard to tell what we're referring to here and technically we're passing an object of values, not props :)
```suggestion
    const value = {
```

2024-06-22 00:43 UTC, cindyquach12 requested changes

2024-06-22 00:43 UTC, cindyquach12 commented on app/contexts/location-and-service/LocationAndService.context.tsx
> +const initialState: LocationAndServiceContextType = {
Let's also keep this name as it was since we're calling this `const initialState` here. And since we can already see that the object is a type, we don't need to specify twice. Calling it `LocationAndServiceProviderState` is more clear that we're housing our state variables here

```suggestion
const initialState: LocationAndServiceContextState = {
```

2024-06-22 00:45 UTC, cvogitgud commented on app/contexts/location-and-service/LocationAndService.context.tsx
> +    const props = {
Ok, sounds good!

2024-06-22 00:46 UTC, cindyquach12 commented on app/contexts/location-and-service/LocationAndService.context.tsx
> +export const useLocationAndService = () => {
Also, just curious why we need to do this instead of calling on the context directly where we need it? 
i.e. `const { location, locationTextInput, service } = useContext(LocationAndServiceContext);`

2024-06-22 00:48 UTC, cvogitgud commented on app/contexts/location-and-service/LocationAndService.context.tsx
> +const initialState: LocationAndServiceContextType = {
Ok, I thought it'd be more clear and consistent with how I see we've been defining types for stuff?
As in `Thing: TypeofThing`, or am I understanding it wrong?

2024-06-22 00:50 UTC, cvogitgud commented on app/contexts/location-and-service/LocationAndService.context.tsx
> +export const useLocationAndService = () => {
It reduces the amount of imports. Without the custom hook, you'd have to import `useContext` and the `LocationAndServiceContext` both every time you want to use the context. This way seems cleaner to me, so that's why I chose to write it like that. What do you think?

2024-06-22 00:54 UTC, cindyquach12 commented on app/contexts/location-and-service/LocationAndService.context.tsx
> +const initialState: LocationAndServiceContextType = {
Well I guess it depends on the context (no pun intended :P). But in this case since it's in the context, I guess it makes more sense to me to name it state since it has all our state. Type would be used more for times like when you need it to define a type (excuse my bad explanation lmao), but basically like how you used `BusinessType` in the `BusinessGrid` file

2024-06-22 00:57 UTC, cindyquach12 commented on app/contexts/location-and-service/LocationAndService.context.tsx
> +export const useLocationAndService = () => {
No I agree, it's a good refactor. Let's pull it out into its own file then since this is a custom hook. We usually would have a separate `hooks.ts` file for these in a hooks folder (that contains all hooks files). 
So just go ahead and create a new hooks folder and you can name the file `locationAndService.hooks.ts` and put that in there

2024-06-22 00:57 UTC, cvogitgud commented on app/contexts/location-and-service/LocationAndService.context.tsx
> +const initialState: LocationAndServiceContextType = {
I'm not sure I totally understand it, but I'll take your word for it!

2024-06-22 00:58 UTC, cvogitgud commented on app/contexts/location-and-service/LocationAndService.context.tsx
> +export const useLocationAndService = () => {
Sounds good.

2024-06-22 01:01 UTC, cindyquach12 commented on app/contexts/location-and-service/LocationAndService.context.tsx
> +const initialState: LocationAndServiceContextType = {
![Screen Shot 2024-06-21 at 6 00 15 PM](https://github.com/cindyquach12/beautyhub/assets/106289033/6dadcd5e-8b0a-4323-9a55-478477cda7c2)
Another example is like this, we name it props b/c we're passing in those values as props to the function, even though it is also a type. This is an example of what I mean when I say it depends on the context (how you're using it)

2024-06-22 01:06 UTC, cindyquach12 commented on app/contexts/location-and-service/LocationAndService.context.tsx
> +const initialState: LocationAndServiceContextType = {
![Screen Shot 2024-06-21 at 6 04 39 PM](https://github.com/cindyquach12/beautyhub/assets/106289033/9e2b9519-5076-4922-87d0-303a5e28481d)
![Screen Shot 2024-06-21 at 6 04 57 PM](https://github.com/cindyquach12/beautyhub/assets/106289033/2aea17f1-55c9-4208-b25c-f00bd82d2581)
The way you're using it here is strictly for the type. In this case, it wouldn't make much sense to pass in `BusinessType` to the `FunctionComponent` as props right? Like in that example above ^
I'm talking about the naming. If you were to pass BusinessType in as props to the FC then you'd change the name to `BusinessGridProps`

2024-06-22 01:10 UTC, cvogitgud commented on app/contexts/location-and-service/LocationAndService.context.tsx
> +const initialState: LocationAndServiceContextType = {
Thanks for the explanation!

2024-06-22 01:10 UTC, cindyquach12 approved these changes

2024-06-22 01:11 UTC, merged