feat: :sparkles: navbar to absolute (incomplete, discuss client vs se…
cindyquach12/beautyhub pull request #3
Opened 2024-05-22 23:49 UTC by cvogitgud

i wanted to add event handling for scrolling on the navbar, but it can't handle interactivity since it uses the Kinde authentication and must be a server side component, thus can't be client side component.

i implemented a Profile component to serve as the menu for when the user is logged in, and it absorbs the LogOut component. i'll handle how it looks when the user isn't logged in later.

2024-05-23 04:08 UTC, cindyquach12 commented
Great job on putting this up! One more thing is, the sticky nav appears to work, but it is completely transparent so you might want to add in some background color so we don't have conflicting overlay as the user scrolls down on the page

2024-05-23 18:38 UTC, cvogitgud commented
I fixed both the transparency and the weird button error that was popping up

2024-05-23 23:48 UTC, cindyquach12 requested changes

2024-05-28 23:41 UTC, cindyquach12 approved these changes
Looks great!

2024-05-28 23:41 UTC, merged