Profile menu routing
cindyquach12/beautyhub pull request #8
Opened 2024-05-29 20:28 UTC by cvogitgud

Added pages for Profile/Account, Settings, Favorites, Reviews, Billing.

2024-05-30 02:02 UTC, cindyquach12 requested changes
Great job!! Just a few comments :)

2024-05-30 02:02 UTC, cindyquach12 commented on app/components/ProfileMenu.tsx
> +                                <LogIn className="size-4 mr-2" /> Log in
or does it even need the Log in text at all?
```suggestion
                                <LogIn className="size-4 mr-2" />
```

2024-05-30 02:02 UTC, cindyquach12 commented on app/not-found.tsx
> +export default function NotFound() {
Let's change this to use `FunctionComponent` and same for the rest of the files

2024-05-30 02:03 UTC, cindyquach12 commented
also, you need to resolve merge conflicts on this branch, lmk if you need help w/ that

2024-05-30 17:54 UTC, cvogitgud commented on app/components/ProfileMenu.tsx
> +                                <LogIn className="size-4 mr-2" /> Log in
LogIn is an icon from lucide-react!

2024-05-30 17:54 UTC, cvogitgud commented on app/components/NavBar.tsx
>  export async function NavBar() {
Got it.

2024-05-30 17:56 UTC, cvogitgud commented on app/components/ProfileMenu.tsx
> +                                <LogIn className="size-4 mr-2" /> Log in
I guess I could make it clearer and use a p or span tag?

2024-05-30 19:04 UTC, cvogitgud commented
merge conflict in ProfileMenu resolved

2024-05-31 01:15 UTC, cindyquach12 approved these changes

2024-05-31 01:15 UTC, merged